[package]
name = "check-ends-macro"
version = "1.0.0"
edition = "2018"
authors = ["DumbMahreeo"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
