[package]
name = "check-ends-macro"
version = "1.0.2"
edition = "2018"
authors = ["DumbMahreeo"]
license = "MIT"
repository = "https://github.com/DumbMahreeo/check-ends-macro."
description = " A couple of macros to simulate match with starts and ends of a string."

[dependencies]
